#!/bin/bash
kernel_image=$1
hd_image=$2

rm -f $hd_image
dd if=/dev/zero of=$hd_image bs=512 count=80640
/sbin/fdisk $hd_image <<EOF
n
p
1


a
p
w
EOF

hd_dev=`sudo /sbin/losetup --show -f $hd_image`
part_dev=`sudo /sbin/losetup --show -f -o 1048576 $hd_image`
tempdir=tmp
sudo /sbin/mke2fs $part_dev
mkdir -p $tempdir
sudo mount -text2 $part_dev $tempdir

sudo mkdir -p $tempdir/boot/grub

sudo grub-install --root-directory=$tempdir --boot-directory=$tempdir/boot --no-floppy --modules="normal part_msdos ext2 multiboot" $hd_dev

sudo cp $kernel_image $tempdir/boot
(
    cat <<EOF
set timeout=15
set default=0

menuentry "Trantor" {
   multiboot /boot/$kernel_image
   boot
}
EOF
) | sudo tee $tempdir/boot/grub/grub.cfg

sudo umount $part_dev
sudo /sbin/losetup -d $part_dev
rmdir $tempdir

sudo /sbin/losetup -d $hd_dev
