#!/bin/bash
kernel_image=$1
fd_image=$2

rm -f $fd_image
dd if=/dev/zero of=$fd_image bs=1024 count=1440

part_dev=`sudo /sbin/losetup --show -f $fd_image`
tempdir=tmp
sudo /sbin/mkfs.fat -v $part_dev
mkdir -p $tempdir
sudo mount -t msdos $part_dev $tempdir
sudo cp $kernel_image $tempdir

sudo umount $part_dev
rmdir $tempdir

sudo /sbin/losetup -d $part_dev
